// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Job struct {
	ID              int64
	Name            string
	Url             string
	Method          interface{}
	Headers         sql.NullString
	IntervalSeconds int64
	NextRunAt       sql.NullTime
	Active          sql.NullBool
}

type JobRun struct {
	ID           int64
	JobID        int64
	Status       sql.NullString
	ResponseCode sql.NullInt64
	ResponseBody sql.NullString
	StartedAt    sql.NullTime
	FinishedAt   sql.NullTime
}
